## Global settings
markdown: redcarpet
permalink : /dojos/:year:month:day
exclude   : ['README.md']

## Local settings
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
title : Coding Dojo / Sergipe
nav   :
  -
    name: Home
    desc: O coding dojo mais recente.
    href: /
  -
    name: Dojos
    desc: Todos os dojos.
    href: /dojos/
  -
    name: GitHub
    desc: Nossos reposit&oacute;rios no GitHub.
    href: //github.com/dojo-se
  -
    name: Google+
    desc: Nossa comunidade no Google+.
    href: //plus.google.com/communities/116253893143706369305
  -
    name: Facebook
    desc: Nossa p&aacute;gina no Facebook.
    href: //facebook.com/dojosergipe
  -
    name: Mailing
    desc: Nossa lista de discuss&atilde;o por email
    href: //groups.google.com/forum/?fromgroups#!forum/dojo-se
